function T = homogeneous_tranfrormation(q,d,l,a)

    T = rotate_coordinate('Z',q) ...
        * translate_coordinate('Z',d)...
        * translate_coordinate('X',l)...
        * rotate_coordinate('X',a)